version: "3.9"

services:
  graphdb:
    image: khaller/graphdb-free
    ports:
      - 7200:7200
    volumes:
      - ./graphDBVolumes/graph-db-data:/opt/graphdb/data
      - ./graphDBVolumes/conf:/opt/graphdb/conf
      - ./graphDBVolumes/log:/opt/graphdb/log
      - ./graphDBVolumes/work:/opt/graphdb/work
