version: "3.9"

services:
  graphdb:
    image: khaller/graphdb-free
    ports:
      - 7200:7200
    volumes:
      - data:/opt/graphdb/data
      - ./graphDB-conf:/opt/graphdb/conf
      - log:/opt/graphdb/log
      - work:/opt/graphdb/work

volumes:
  data:
  log:
  work:
